networks:
  mir:
    driver: bridge

services:
  master_db:
    image: mysql:8.0.23
    container_name: mir_master_db
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      - ./db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    networks:
      mir:
        aliases:
          - master_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mir_master_db_admin
    ports:
      - "8010:80"
    environment:
      PMA_HOST: master_db
    links:
      - master_db
    depends_on:
      - master_db
    networks:
      - mir
