/*
 * Generated by ISE 16.05.9.8969 GPL Edition - linux-x86-64
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F222_6321();
extern void F224_6475();
extern void F229_6544();
extern void F230_6684();
extern void F301_3609();
extern void F255_6202();
extern void F112_1575();
extern EIF_REFERENCE F112_1562();
extern EIF_BOOLEAN F112_1574();
extern EIF_BOOLEAN F112_1579();
extern void F112_1584();
extern void F112_1585();
extern void F112_1586();
extern void F45_1105();
extern EIF_TYPED_VALUE F45_1106();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F222_6321;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F229_6544;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F301_3609;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F224_6475;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F230_6684;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F255_6202;
	egc_is_scoop_capable = 0;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F112_1575;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F112_1574;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F112_1562;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F112_1579;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F112_1584;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F112_1585;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F112_1586;

	egc_str_dtype = 223;

	egc_str32_dtype = 229;
	egc_arr_dtype = 300;
	egc_tup_dtype = 177;
	egc_disp_rout_id = 2828;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x019D;
	egc_sp_wchar = 0x025E;
	egc_sp_bool = 0x017A;
	egc_sp_uint8 = 0x01D3;
	egc_sp_uint16 = 0x021E;
	egc_sp_uint32 = 0x0326;
	egc_sp_uint64 = 0x02CC;
	egc_sp_int8 = 0x0344;
	egc_sp_int16 = 0x0367;
	egc_sp_int32 = 0x02A2;
	egc_sp_int64 = 0x038A;
	egc_sp_real32 = 0x0157;
	egc_sp_real64 = 0x0254;
	egc_sp_pointer = 0x0277;
	egc_sp_ref = 0x0131;

	egc_uint8_dtype = 197;
	egc_uint16_dtype = 209;
	egc_uint32_dtype = 206;
	egc_uint64_dtype = 215;
	egc_int8_dtype = 179;
	egc_int16_dtype = 203;
	egc_int32_dtype = 212;
	egc_int64_dtype = 188;
	egc_bool_dtype = 191;
	egc_real32_dtype = 200;
	egc_char_dtype = 185;
	egc_wchar_dtype = 182;
	egc_real64_dtype = 194;
	egc_point_dtype = 218;

	egc_exception_dtype = 61;
	egc_except_emnger_dtype = 111;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "business_card";
	egc_system_location = "/home/worm2fed/Documents/Study/Innopolis/Introduction to Programming/assignment_1/business_card/EIFGENs/business_card/W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1474067989;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 954;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "BUSINESS_CARD.fill_in";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 4949;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 44;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F45_1105;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F45_1106;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 953; /* BUSINESS_CARD */
	}
}

#ifdef __cplusplus
}
#endif
